packages:
  - "packages/*"
blockExoticSubdeps: false
catalog:
  "fvtt-types": "14.366.0-beta.20260926212002"
  "vite": "^8.3.1"
  "vitest": "^5.0.2"

  # - "@types/earcut": "3.0.0"
  # - "vite": "$vite"
  # - "@types/react": "$@types/react"
overrides:
  fvtt-types: "catalog:"
  vite: "catalog:"
  vitest: "catalog:"
allowBuilds:
  "@parcel/watcher": true
  "@swc/core": true
  classic-level: true
  esbuild: true
  fvtt-types: true
