name: CI/CD

on:
  - push
  - pull_request

env:
  MANIFEST_FILE_NAME: "system.json"
  PUBLIC_PATH: "public"
  PACKAGE_FILE_NAME: "pub-crusade.zip"
  PACKAGE_PATH: package
  DOWNLOAD_BASE: "https://github.com/${{github.repository}}/releases/download"

jobs:
  pre_job:
    # see https://github.com/marketplace/actions/skip-duplicate-actions
    # prevents duplicate workflow runs when they get triggered by e.g. `push`
    # and `pull_request` events
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5.3.1
        with:
          concurrent_skipping: same_content_newer

  ci-cd:
    # annoyingly, reusable workflows have to be in .github/workflows, either of
    # the local repo or a shared repo. There's literally no way of referencing
    # a reusable workflow in another folder, maing it impossible to use shared
    # workflows in subfolders (i.e. subrepos like we have.) Symlinks do not
    # work (GH does not follow them) so we are left referencing the
    # shared-fvtt-bits repo like this. See this discussion:
    # https://github.com/orgs/community/discussions/9050
    # Reusable workflows docs:
    # https://docs.github.com/en/actions/using-workflows/reusing-workflows
    uses: lumphammer/gh-actions/.github/workflows/ci-cd-reusable.yml@2024-11-24.2
    needs: pre_job
    # skip the job is it a duplicate, but not if it's a tag (we always want to
    # make sure we build a tag so we get a release.)
    if: needs.pre_job.outputs.should_skip != 'true' || github.ref_type == 'tag'
    permissions:
      contents: write
    with:
      manifest_file_name: "system.json"
      public_path: "public"
      package_id: "pub-crusade"
      pnpm_version: "9"
      package_path: "build_package"
      foundry_package_release: false
      release_to_bucket: false
